name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASS: ${{ secrets.SERVER_PASS }}
        SERVER_URL: ${{ secrets.SERVER_URL }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_JSON_KEY }}

    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        name: microservice-mailer-nest
        runtime: nodejs18
        entry_point: microservice_mailer_nest
        memory_mb: 256
        region: southamerica-east1
        env_vars:
          SERVER_USER=${{ secrets.SERVER_USER }}
          SERVER_PASS=${{ secrets.SERVER_PASS }}
          SERVER_URL=${{ secrets.SERVER_URL }}
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}
          
    # Example of using the output
    - id: test
      run: curl "${{ steps.deploy.outputs.url }}"

